[package]
name = "monorail"
version = "0.1.0"
authors = ["jndean <josefdean@blueyonder.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.2.3"
num-bigint = "0.2.6"
regex = "1"